IF (SELECT OBJECT_ID('[ext].[BTC_SECTION]')) IS NULL 
BEGIN
    CREATE TABLE [ext].[BTC_SECTION]
    (
        [SECTIONID] NVARCHAR(100) NOT NULL,
        [NAME] NVARCHAR(100) NOT NULL,
        [DESCRIPTION] NVARCHAR(100) NOT NULL,
        [CODE] NVARCHAR(100) NOT NULL,
        [ORDERID] NVARCHAR(100) NOT NULL,
        [STATUS] NVARCHAR(100) NOT NULL,
        [CAPACITY] NVARCHAR(100) NOT NULL,
        [FLOORNUMBER] INT NULL,                  
        [ISOUTDOOR] Int NOT NULL DEFAULT 0,         
        [SPECIALFEATURES] NVARCHAR(255) NULL,
        [LASTUPDATED] NVARCHAR (100),
        [STORE] NVARCHAR (100),
        [CHANNELID] NVARCHAR (100),
        [DATAAREAID] NVARCHAR(10) NOT NULL,
        CONSTRAINT [I_BTC_SECTION_PK] PRIMARY KEY CLUSTERED ([SECTIONID] ASC)
    ) ON [PRIMARY]
END
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[BTC_SECTION] TO [UsersRole];
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[BTC_SECTION] TO [DataSyncUsersRole];
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[BTC_SECTION] TO [DeployExtensibilityRole];
GO



IF (SELECT OBJECT_ID('[ext].[BTC_TABLEDETAILS]')) IS NULL 
BEGIN
CREATE TABLE [ext].[BTC_TABLEDETAILS](
    [BTC_TABLEID] [int] NOT NULL DEFAULT ((0)),
    [TABLENAME] [nvarchar](100) NOT NULL DEFAULT (''), 
    [CAPACITY] [int] NOT NULL DEFAULT ((0)),
    [ISOCCUPIED] [int] NOT NULL  DEFAULT ((0)),
    [ISCHECKEDOUT] [int] NOT NULL  DEFAULT ((0)),
    [ISMERGED] [int] NOT NULL  DEFAULT ((0)),
    [CREATEDON] [nvarchar] (100) NOT NULL DEFAULT (0),
    [RECID] [bigint] NOT NULL DEFAULT ((0)),
    [DATAAREAID] [nvarchar](10) NULL,
    [ISBLOCKED] [int] NOT NULL DEFAULT ((0)),
 CONSTRAINT [I_BTC_TABLEDETAILS_PK] PRIMARY KEY CLUSTERED ([RECID] ASC)
    ) ON [PRIMARY]
END
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[BTC_TABLEDETAILS] TO [DATASYNCUSERSROLE]
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[BTC_TABLEDETAILS] TO [USERSROLE]
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[BTC_TABLEDETAILS] TO [DEPLOYEXTENSIBILITYROLE]
GO

ALTER TABLE [ext].[BTC_TABLEDETAILS] 
ADD SECTIONID NVARCHAR(100) NOT NULL DEFAULT ('');

-- Add the total number of tables in a section
ALTER TABLE [ext].[BTC_TABLEDETAILS]
ADD TABLESINSECTION INT NOT NULL DEFAULT ((0)); -- Number of tables in a section

-- Add a field to store the number of chairs for each table
ALTER TABLE [ext].[BTC_TABLEDETAILS]
ADD CHAIRCOUNT INT NOT NULL DEFAULT ((0)); -- Number of chairs for the table
